# Generated by Django 5.2.10 on 2026-02-05 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessgrant',
            options={'permissions': [('can_grant_access', 'Can grant access to resource'), ('can_revoke_access', 'Can revoke access grants')]},
        ),
    ]
