# Generated by Django 5.2.10 on 2026-02-23 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('resource_created', 'Resource created'), ('resource_updated', 'Resource updated'), ('resource_deleted', 'Resource deleted'), ('grant_created', 'Grant created'), ('grant_revoked', 'Grant revoked'), ('grant_expired', 'Grant expired'), ('user_created', 'User created'), ('user_activated', 'User activated'), ('user_deactivated', 'User deactivate')], max_length=20)),
                ('object_type', models.CharField(max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('object_repr', models.CharField(max_length=80)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
