# Generated by Django 5.2.10 on 2026-06-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_auditlog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('resource_created', 'Resource created'), ('resource_updated', 'Resource updated'), ('resource_deleted', 'Resource deleted'), ('grant_created', 'Grant created'), ('grant_revoked', 'Grant revoked'), ('grant_expired', 'Grant expired'), ('user_created', 'User created'), ('user_activated', 'User activated'), ('user_deactivated', 'User deactivated'), ('user_updated', 'User updated'), ('password_changed', 'Password changed')], max_length=20),
        ),
    ]
